version: "3.7"
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - "8081:8081"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "JAVA_OPTS=-Djboss.http.port=8081"
      - "DB_VENDOR=mysql"
      - "DB_ADDR=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_PASSWORD=changeme"
    networks:
      - ${GLOBAL_NETWORK:-keycloak}